name: 'assurance_learn'
version: '1.0.0'

profile: 'assurance_learn'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
snapshot-paths: ["snapshots"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  assurance_learn:
    staging:
      +schema: staging
      +materialized: view
      +tags:
        - daily
    intermediate:
      +schema: intermediate
      +materialized: view
      +tags:
        - daily
    marts:
      +schema: gold
      +materialized: table
      +tags:
        - daily


seeds:  
  assurance_learn:
    +schema: seeds


snapshots:  
  assurance_learn:
    +schema: snapshots
    +tags:
      - weekly


tests:
  assurance_learn:
    +store_failures: true
    +schema: test_failures